name: app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.2
  url_launcher: ^6.0.18
  wallet_connect: ^1.0.2
  web3dart: ^2.3.0 
  qr_flutter: ^4.0.0
  uuid: ^3.0.5 
  cryptography: ^2.0.5
  convert: ^3.0.1
  flutter_dotenv: ^5.0.2
  pointycastle: ^3.5.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  crypto: ^3.0.1
  x25519: ^0.1.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - .env
